In [45]:

import pandas as pd
import glob
import dateutil.parser as dparser

In [46]:
# import cbonds list
cbonds_path = r'/Users/Danny/Desktop/MDA_proyect/Datasets/HISTORICAL_BONDS.csv'
cbonds = pd.read_csv(cbonds_path, index_col=None, header=0)

In [47]:
q2_2017_path = r'/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2017/Q2'
q3_2017_path = r'/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2017/Q3'
q4_2017_path = r'/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2017/Q4'
q1_2018_path = r'/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2018/Q1'
q2_2018_path = r'/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2018/Q2'
q3_2018_path = r'/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2018/Q3'
q4_2018_path = r'/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2018/Q4'
q1_2019_path = r'/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2019/Q1'
q2_2019_path = r'/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2019/Q2'
q3_2019_path = r'/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2019/Q3'
q4_2019_path = r'/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2019/Q4'
q1_2020_path = r'/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2020/Q1'
q2_2020_path = r'/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2020/Q2'
q3_2020_path = r'/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2020/Q3'
q4_2020_path = r'/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2020/Q4'
q1_2021_path = r'/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2021/Q1'
q2_2021_path = r'/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2021/Q2'

list_of_paths = [q2_2017_path, q3_2017_path, q4_2017_path, 
                 q1_2018_path, q2_2018_path, q3_2018_path, 
                 q4_2018_path, q1_2019_path, q2_2019_path, 
                 q3_2019_path, q4_2019_path, q1_2020_path, 
                 q2_2020_path, q3_2020_path, q4_2020_path, 
                 q1_2021_path, q2_2021_path]
list_of_paths

['/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2017/Q2',
 '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2017/Q3',
 '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2017/Q4',
 '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2018/Q1',
 '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2018/Q2',
 '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2018/Q3',
 '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2018/Q4',
 '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2019/Q1',
 '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2019/Q2',
 '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2019/Q3',
 '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2019/Q4',
 '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2020/Q1',
 '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2020/Q2',
 '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2020/Q3',
 '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2020/Q4',
 '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2021/Q1',
 '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2021/Q2']

In [48]:
q2_2017_path = r'/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2017/Q2'
q2_2017_path

'/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2017/Q2'

In [49]:
complete_list = []

In [50]:
for path in list_of_paths:
    all_files = glob.glob(path + "/*.csv")
    complete_list.append(all_files)

complete_list

[['/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2017/Q2\\CSPPholdings_20170623.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2017/Q2\\CSPPholdings_20170630.csv'],
 ['/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2017/Q3\\CSPPholdings_20170707.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2017/Q3\\CSPPholdings_20170714.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2017/Q3\\CSPPholdings_20170721.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2017/Q3\\CSPPholdings_20170728.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2017/Q3\\CSPPholdings_20170804.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2017/Q3\\CSPPholdings_20170811.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2017/Q3\\CSPPholdings_20170818.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2017/Q3\\CSPPholdings_20170825.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2017/Q3\\CSPPholdings_20170901.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2017/Q3\\CSPPholdings_20170908.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2017/Q3\\CSPPholdings_20170915.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2017/Q3\\CSPPholdings_20170922.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2017/Q3\\CSPPholdings_20170929.csv'],
 ['/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2017/Q4\\CSPPholdings_20171006.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2017/Q4\\CSPPholdings_20171013.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2017/Q4\\CSPPholdings_20171020.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2017/Q4\\CSPPholdings_20171027.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2017/Q4\\CSPPholdings_20171103.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2017/Q4\\CSPPholdings_20171110.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2017/Q4\\CSPPholdings_20171117.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2017/Q4\\CSPPholdings_20171124.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2017/Q4\\CSPPholdings_20171201.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2017/Q4\\CSPPholdings_20171208.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2017/Q4\\CSPPholdings_20171215.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2017/Q4\\CSPPholdings_20171222.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2017/Q4\\CSPPholdings_20171229.csv'],
 ['/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2018/Q1\\CSPPholdings_20180105.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2018/Q1\\CSPPholdings_20180112.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2018/Q1\\CSPPholdings_20180119.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2018/Q1\\CSPPholdings_20180126.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2018/Q1\\CSPPholdings_20180202.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2018/Q1\\CSPPholdings_20180209.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2018/Q1\\CSPPholdings_20180216.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2018/Q1\\CSPPholdings_20180223.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2018/Q1\\CSPPholdings_20180302.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2018/Q1\\CSPPholdings_20180309.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2018/Q1\\CSPPholdings_20180316.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2018/Q1\\CSPPholdings_20180323.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2018/Q1\\CSPPholdings_20180330.csv'],
 ['/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2018/Q2\\CSPPholdings_20180406.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2018/Q2\\CSPPholdings_20180413.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2018/Q2\\CSPPholdings_20180420.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2018/Q2\\CSPPholdings_20180427.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2018/Q2\\CSPPholdings_20180504.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2018/Q2\\CSPPholdings_20180511.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2018/Q2\\CSPPholdings_20180518.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2018/Q2\\CSPPholdings_20180525.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2018/Q2\\CSPPholdings_20180601.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2018/Q2\\CSPPholdings_20180608.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2018/Q2\\CSPPholdings_20180615.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2018/Q2\\CSPPholdings_20180622.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2018/Q2\\CSPPholdings_20180629.csv'],
 ['/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2018/Q3\\CSPPholdings_20180706.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2018/Q3\\CSPPholdings_20180713.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2018/Q3\\CSPPholdings_20180720.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2018/Q3\\CSPPholdings_20180727.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2018/Q3\\CSPPholdings_20180803.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2018/Q3\\CSPPholdings_20180810.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2018/Q3\\CSPPholdings_20180817.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2018/Q3\\CSPPholdings_20180824.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2018/Q3\\CSPPholdings_20180831.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2018/Q3\\CSPPholdings_20180907.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2018/Q3\\CSPPholdings_20180914.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2018/Q3\\CSPPholdings_20180921.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2018/Q3\\CSPPholdings_20180928.csv'],
 ['/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2018/Q4\\CSPPholdings_20181005.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2018/Q4\\CSPPholdings_20181012.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2018/Q4\\CSPPholdings_20181019.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2018/Q4\\CSPPholdings_20181026.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2018/Q4\\CSPPholdings_20181102.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2018/Q4\\CSPPholdings_20181109.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2018/Q4\\CSPPholdings_20181116.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2018/Q4\\CSPPholdings_20181123.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2018/Q4\\CSPPholdings_20181130.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2018/Q4\\CSPPholdings_20181207.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2018/Q4\\CSPPholdings_20181214.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2018/Q4\\CSPPholdings_20181221.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2018/Q4\\CSPPholdings_20181228.csv'],
 ['/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2019/Q1\\CSPPholdings_20190104.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2019/Q1\\CSPPholdings_20190111.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2019/Q1\\CSPPholdings_20190118.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2019/Q1\\CSPPholdings_20190125.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2019/Q1\\CSPPholdings_20190201.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2019/Q1\\CSPPholdings_20190208.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2019/Q1\\CSPPholdings_20190215.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2019/Q1\\CSPPholdings_20190222.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2019/Q1\\CSPPholdings_20190301.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2019/Q1\\CSPPholdings_20190308.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2019/Q1\\CSPPholdings_20190315.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2019/Q1\\CSPPholdings_20190322.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2019/Q1\\CSPPholdings_20190329.csv'],
 ['/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2019/Q2\\CSPPholdings_20190405.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2019/Q2\\CSPPholdings_20190412.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2019/Q2\\CSPPholdings_20190419.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2019/Q2\\CSPPholdings_20190426.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2019/Q2\\CSPPholdings_20190503.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2019/Q2\\CSPPholdings_20190510.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2019/Q2\\CSPPholdings_20190517.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2019/Q2\\CSPPholdings_20190524.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2019/Q2\\CSPPholdings_20190531.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2019/Q2\\CSPPholdings_20190607.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2019/Q2\\CSPPholdings_20190614.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2019/Q2\\CSPPholdings_20190621.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2019/Q2\\CSPPholdings_20190628.csv'],
 ['/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2019/Q3\\CSPPholdings_20190705.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2019/Q3\\CSPPholdings_20190712.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2019/Q3\\CSPPholdings_20190719.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2019/Q3\\CSPPholdings_20190726.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2019/Q3\\CSPPholdings_20190802.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2019/Q3\\CSPPholdings_20190809.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2019/Q3\\CSPPholdings_20190816.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2019/Q3\\CSPPholdings_20190823.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2019/Q3\\CSPPholdings_20190830.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2019/Q3\\CSPPholdings_20190906.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2019/Q3\\CSPPholdings_20190913.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2019/Q3\\CSPPholdings_20190920.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2019/Q3\\CSPPholdings_20190927.csv'],
 ['/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2019/Q4\\CSPPholdings_20191004.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2019/Q4\\CSPPholdings_20191011.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2019/Q4\\CSPPholdings_20191018.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2019/Q4\\CSPPholdings_20191025.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2019/Q4\\CSPPholdings_20191101.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2019/Q4\\CSPPholdings_20191108.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2019/Q4\\CSPPholdings_20191115.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2019/Q4\\CSPPholdings_20191122.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2019/Q4\\CSPPholdings_20191129.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2019/Q4\\CSPPholdings_20191206.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2019/Q4\\CSPPholdings_20191213.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2019/Q4\\CSPPholdings_20191220.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2019/Q4\\CSPPholdings_20191227.csv'],
 ['/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2020/Q1\\CSPPholdings_20200103.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2020/Q1\\CSPPholdings_20200110.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2020/Q1\\CSPPholdings_20200117.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2020/Q1\\CSPPholdings_20200124.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2020/Q1\\CSPPholdings_20200131.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2020/Q1\\CSPPholdings_20200207.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2020/Q1\\CSPPholdings_20200214.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2020/Q1\\CSPPholdings_20200221.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2020/Q1\\CSPPholdings_20200228.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2020/Q1\\CSPPholdings_20200306.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2020/Q1\\CSPPholdings_20200313.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2020/Q1\\CSPPholdings_20200320.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2020/Q1\\CSPPholdings_20200327.csv'],
 ['/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2020/Q2\\CSPP_PEPP_corporate_bond_holdings_20200403.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2020/Q2\\CSPP_PEPP_corporate_bond_holdings_20200410.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2020/Q2\\CSPP_PEPP_corporate_bond_holdings_20200417.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2020/Q2\\CSPP_PEPP_corporate_bond_holdings_20200424.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2020/Q2\\CSPP_PEPP_corporate_bond_holdings_20200501.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2020/Q2\\CSPP_PEPP_corporate_bond_holdings_20200508.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2020/Q2\\CSPP_PEPP_corporate_bond_holdings_20200515.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2020/Q2\\CSPP_PEPP_corporate_bond_holdings_20200522.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2020/Q2\\CSPP_PEPP_corporate_bond_holdings_20200529.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2020/Q2\\CSPP_PEPP_corporate_bond_holdings_20200605.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2020/Q2\\CSPP_PEPP_corporate_bond_holdings_20200612.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2020/Q2\\CSPP_PEPP_corporate_bond_holdings_20200619.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2020/Q2\\CSPP_PEPP_corporate_bond_holdings_20200626.csv'],
 ['/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2020/Q3\\CSPP_PEPP_corporate_bond_holdings_20200703.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2020/Q3\\CSPP_PEPP_corporate_bond_holdings_20200710.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2020/Q3\\CSPP_PEPP_corporate_bond_holdings_20200717.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2020/Q3\\CSPP_PEPP_corporate_bond_holdings_20200724.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2020/Q3\\CSPP_PEPP_corporate_bond_holdings_20200731.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2020/Q3\\CSPP_PEPP_corporate_bond_holdings_20200807.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2020/Q3\\CSPP_PEPP_corporate_bond_holdings_20200814.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2020/Q3\\CSPP_PEPP_corporate_bond_holdings_20200821.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2020/Q3\\CSPP_PEPP_corporate_bond_holdings_20200828.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2020/Q3\\CSPP_PEPP_corporate_bond_holdings_20200904.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2020/Q3\\CSPP_PEPP_corporate_bond_holdings_20200911.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2020/Q3\\CSPP_PEPP_corporate_bond_holdings_20200918.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2020/Q3\\CSPP_PEPP_corporate_bond_holdings_20200925.csv'],
 ['/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2020/Q4\\CSPP_PEPP_corporate_bond_holdings_20201002.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2020/Q4\\CSPP_PEPP_corporate_bond_holdings_20201009.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2020/Q4\\CSPP_PEPP_corporate_bond_holdings_20201016.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2020/Q4\\CSPP_PEPP_corporate_bond_holdings_20201023.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2020/Q4\\CSPP_PEPP_corporate_bond_holdings_20201030.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2020/Q4\\CSPP_PEPP_corporate_bond_holdings_20201106.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2020/Q4\\CSPP_PEPP_corporate_bond_holdings_20201113.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2020/Q4\\CSPP_PEPP_corporate_bond_holdings_20201120.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2020/Q4\\CSPP_PEPP_corporate_bond_holdings_20201127.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2020/Q4\\CSPP_PEPP_corporate_bond_holdings_20201204.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2020/Q4\\CSPP_PEPP_corporate_bond_holdings_20201211.csv',
  '/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2020/Q4\\CSPP_PEPP_corporate_bond_holdings_20201218.csv'],
 ['/Users/Danny/Desktop/MDA_proyect/Datasets/historical_lists_cspp/2021/Q1\\CSPP_PEPP_corporate_bond_holdings_20210108.csv',

In [51]:
list_of_df_names = ["q2_2017_df", "q3_2017_df", "q4_2017_df", "q1_2018_df", 
 "q2_2018_df", "q3_2018_df", "q4_2018_df", "q1_2019_df", 
 "q2_2019_df", "q3_2019_df", "q4_2019_df", "q1_2020_df", 
 "q2_2020_df", "q3_2020_df", "q4_2020_df", "q1_2021_df", 
 "q2_2021_df"]
list_of_df_names

['q2_2017_df',
 'q3_2017_df',
 'q4_2017_df',
 'q1_2018_df',
 'q2_2018_df',
 'q3_2018_df',
 'q4_2018_df',
 'q1_2019_df',
 'q2_2019_df',
 'q3_2019_df',
 'q4_2019_df',
 'q1_2020_df',
 'q2_2020_df',
 'q3_2020_df',
 'q4_2020_df',
 'q1_2021_df',
 'q2_2021_df']

In [52]:
all_historical_data = []
df_names = []

In [53]:
for i in range(len(list_of_df_names)):
    link_length = len(complete_list[i])
    df_name = list_of_df_names[i]
    for l in range(link_length):
        individual_csv = complete_list[i][l]
        csv_name = complete_list[i][l][-12:]
        csv = pd.read_csv(individual_csv, encoding='latin-1')
        all_historical_data.append(csv)
        df_names.append(csv_name)

In [54]:
all_historical_data[1]

,NCB,ISIN_CODE,ISSUER_NAME_,MATURITY_DATE_,COUPON_RATE_
0,IT,XS1088274169,2i Rete Gas S.p.A.,16/07/2019,1.750
1,IT,XS1088274672,2i Rete Gas S.p.A.,16/07/2024,3.000
2,IT,XS1144492532,2i Rete Gas S.p.A.,02/01/2020,1.125
3,IT,XS1571982468,2i Rete Gas S.p.A.,28/08/2026,1.750
4,IT,XS0859920406,A2A S.p.A.,28/11/2019,4.500
...,...,...,...,...,...
969,DE,XS1234248919,Würth Finance International BV,19/05/2022,1.000
970,BE,XS0979598207,Západoslovenská energetika AS,14/10/2018,2.875
971,BE,XS0979598462,Západoslovenská energetika AS,14/10/2023,4.000
972,NaN,NaN,NaN,NaN,NaN
973,*coupons are rounded to the third decimal,NaN,NaN,NaN,NaN

In [55]:
for n in range(len(df_names)):
    week_gathered = df_names[n]
    all_historical_data[n]["historical_date"] = week_gathered

In [56]:
# all_historical_data

In [57]:
all_historical_copies = pd.concat(all_historical_data)

In [58]:
all_historical_copies

,NCB,ISIN_CODE,ISSUER_NAME_,MATURITY_DATE_,COUPON_RATE_*,historical_date,COUPON_RATE_,ISSUER_NAME,MATURITY_DATE,COUPON_RATE,Unnamed: 5,Unnamed: 6,Unnamed: 0,ISIN,ISSUER,MATURITY DATE,COUPON RATE
0,IT,XS1088274169,2i Rete Gas S.p.A.,16/07/2019,1.75,20170623.csv,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,IT,XS1088274672,2i Rete Gas S.p.A.,16/07/2024,3,20170623.csv,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,IT,XS1144492532,2i Rete Gas S.p.A.,02/01/2020,1.125,20170623.csv,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,IT,XS1571982468,2i Rete Gas S.p.A.,28/08/2026,1.75,20170623.csv,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,IT,XS0859920406,A2A S.p.A.,28/11/2019,4.5,20170623.csv,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1656,IT,NaN,NaN,NaN,NaN,20210507.csv,NaN,NaN,NaN,NaN,NaN,NaN,NaN,XS2299001888,Italgas S.P.A.,16/02/2028,0
1657,IT,NaN,NaN,NaN,NaN,20210507.csv,NaN,NaN,NaN,NaN,NaN,NaN,NaN,XS2299002423,Italgas S.P.A.,16/02/2033,0.5
1658,IT,NaN,NaN,NaN,NaN,20210507.csv,NaN,NaN,NaN,NaN,NaN,NaN,NaN,XS2300208928,Snam S.p.A.,15/08/2025,0
1659,IT,NaN,NaN,NaN,NaN,20210507.csv,NaN,NaN,NaN,NaN,NaN,NaN,NaN,XS2324772453,Ferrovie dello Stato Ital.SpA,25/03/2028,0.375
1660,IT,NaN,NaN,NaN,NaN,20210507.csv,NaN,NaN,NaN,NaN,NaN,NaN,NaN,XS2332687040,Infrastrutture Wireless Italiane S.p.A,19/04/2031,1.75

In [59]:
all_historical_copies["ISIN_Code"] = all_historical_copies["ISIN_CODE"].astype(str) + all_historical_copies["ISIN"].astype(str)
all_historical_copies["Issuer_Name"] = all_historical_copies["ISSUER_NAME_"].astype(str) + all_historical_copies["ISSUER_NAME"].astype(str) + all_historical_copies["ISSUER"].astype(str)
all_historical_copies["Maturity_Date"] = all_historical_copies["MATURITY_DATE_"].astype(str) + all_historical_copies["MATURITY_DATE"].astype(str) + all_historical_copies["MATURITY DATE"].astype(str)
all_historical_copies["Coupon_Rate"] = all_historical_copies["COUPON_RATE_"].astype(str) + all_historical_copies["COUPON_RATE_*"].astype(str) + all_historical_copies["COUPON_RATE"].astype(str) + all_historical_copies["COUPON RATE"].astype(str)

In [60]:
all_historical_copies

,NCB,ISIN_CODE,ISSUER_NAME_,MATURITY_DATE_,COUPON_RATE_*,historical_date,COUPON_RATE_,ISSUER_NAME,MATURITY_DATE,COUPON_RATE,...,Unnamed: 6,Unnamed: 0,ISIN,ISSUER,MATURITY DATE,COUPON RATE,ISIN_Code,Issuer_Name,Maturity_Date,Coupon_Rate
0,IT,XS1088274169,2i Rete Gas S.p.A.,16/07/2019,1.75,20170623.csv,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,XS1088274169nan,2i Rete Gas S.p.A.nannan,16/07/2019nannan,nan1.75nannan
1,IT,XS1088274672,2i Rete Gas S.p.A.,16/07/2024,3,20170623.csv,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,XS1088274672nan,2i Rete Gas S.p.A.nannan,16/07/2024nannan,nan3nannan
2,IT,XS1144492532,2i Rete Gas S.p.A.,02/01/2020,1.125,20170623.csv,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,XS1144492532nan,2i Rete Gas S.p.A.nannan,02/01/2020nannan,nan1.125nannan
3,IT,XS1571982468,2i Rete Gas S.p.A.,28/08/2026,1.75,20170623.csv,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,XS1571982468nan,2i Rete Gas S.p.A.nannan,28/08/2026nannan,nan1.75nannan
4,IT,XS0859920406,A2A S.p.A.,28/11/2019,4.5,20170623.csv,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,XS0859920406nan,A2A S.p.A.nannan,28/11/2019nannan,nan4.5nannan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1656,IT,NaN,NaN,NaN,NaN,20210507.csv,NaN,NaN,NaN,NaN,...,NaN,NaN,XS2299001888,Italgas S.P.A.,16/02/2028,0,nanXS2299001888,nannanItalgas S.P.A.,nannan16/02/2028,nannannan0
1657,IT,NaN,NaN,NaN,NaN,20210507.csv,NaN,NaN,NaN,NaN,...,NaN,NaN,XS2299002423,Italgas S.P.A.,16/02/2033,0.5,nanXS2299002423,nannanItalgas S.P.A.,nannan16/02/2033,nannannan0.5
1658,IT,NaN,NaN,NaN,NaN,20210507.csv,NaN,NaN,NaN,NaN,...,NaN,NaN,XS2300208928,Snam S.p.A.,15/08/2025,0,nanXS2300208928,nannanSnam S.p.A.,nannan15/08/2025,nannannan0
1659,IT,NaN,NaN,NaN,NaN,20210507.csv,NaN,NaN,NaN,NaN,...,NaN,NaN,XS2324772453,Ferrovie dello Stato Ital.SpA,25/03/2028,0.375,nanXS2324772453,nannanFerrovie dello Stato Ital.SpA,nannan25/03/2028,nannannan0.375
1660,IT,NaN,NaN,NaN,NaN,20210507.csv,NaN,NaN,NaN,NaN,...,NaN,NaN,XS2332687040,Infrastrutture Wireless Italiane S.p.A,19/04/2031,1.75,nanXS2332687040,nannanInfrastrutture Wireless Italiane S.p.A,nannan19/04/2031,nannannan1.75

In [61]:
# list(all_historical_copies.columns.values)

In [62]:
all_historical_copies = all_historical_copies.drop(columns=['ISIN_CODE',
                                                            'ISSUER_NAME_',
                                                            'MATURITY_DATE_',
                                                            'COUPON_RATE_',
                                                            'COUPON_RATE_*',
                                                            'ISSUER_NAME',
                                                            'MATURITY_DATE',
                                                            'COUPON_RATE',
                                                            'Unnamed: 5',
                                                            'Unnamed: 6',
                                                            'Unnamed: 0',
                                                            'ISIN',
                                                            'ISSUER',
                                                            'MATURITY DATE',
                                                            'COUPON RATE'])

In [63]:
all_historical_copies = all_historical_copies.reset_index(drop = True)

In [64]:
all_historical_copies.loc[0]["historical_date"]

'20170623.csv'

In [65]:
all_historical_copies.head()

,NCB,historical_date,ISIN_Code,Issuer_Name,Maturity_Date,Coupon_Rate
0,IT,20170623.csv,XS1088274169nan,2i Rete Gas S.p.A.nannan,16/07/2019nannan,nan1.75nannan
1,IT,20170623.csv,XS1088274672nan,2i Rete Gas S.p.A.nannan,16/07/2024nannan,nan3nannan
2,IT,20170623.csv,XS1144492532nan,2i Rete Gas S.p.A.nannan,02/01/2020nannan,nan1.125nannan
3,IT,20170623.csv,XS1571982468nan,2i Rete Gas S.p.A.nannan,28/08/2026nannan,nan1.75nannan
4,IT,20170623.csv,XS0859920406nan,A2A S.p.A.nannan,28/11/2019nannan,nan4.5nannan

In [66]:
# split the dataframes into

In [67]:
for row in range(len(all_historical_copies)):
    all_historical_copies.iloc[row, 1] = all_historical_copies.loc[row]["historical_date"].replace('.csv', '')
    all_historical_copies.iloc[row, 2] = all_historical_copies.loc[row]["ISIN_Code"].replace('nan', '')
    all_historical_copies.iloc[row, 3] = all_historical_copies.loc[row]["Issuer_Name"].replace('nan', '')
#     all_historical_copies.iloc[row, 3] = all_historical_copies.loc[row]["Issuer_Name"].replace('nannan', '')
    all_historical_copies.iloc[row, 4] = all_historical_copies.loc[row]["Maturity_Date"].replace('nan', '')
#     all_historical_copies.iloc[row, 4] = all_historical_copies.loc[row]["Maturity_Date"].replace('nannan', '')
    all_historical_copies.iloc[row, 5] = all_historical_copies.loc[row]["Coupon_Rate"].replace('nan', '')
#     all_historical_copies.iloc[row, 5] = all_historical_copies.loc[row]["Coupon_Rate"].replace('nannan', '')
#     all_historical_copies.iloc[row, 5] = all_historical_copies.loc[row]["Coupon_Rate"].replace('nannannan', '')

In [68]:
all_historical_copies.head()

,NCB,historical_date,ISIN_Code,Issuer_Name,Maturity_Date,Coupon_Rate
0,IT,20170623,XS1088274169,2i Rete Gas S.p.A.,16/07/2019,1.75
1,IT,20170623,XS1088274672,2i Rete Gas S.p.A.,16/07/2024,3
2,IT,20170623,XS1144492532,2i Rete Gas S.p.A.,02/01/2020,1.125
3,IT,20170623,XS1571982468,2i Rete Gas S.p.A.,28/08/2026,1.75
4,IT,20170623,XS0859920406,A2A S.p.A.,28/11/2019,4.5

In [69]:
len(all_historical_copies)

255918

In [70]:
all_isin_codes = all_historical_copies["ISIN_Code"].tolist()

In [71]:
# all_isin_codes

In [72]:
cbonds_isin_list = cbonds["ISIN"].tolist()

In [73]:
# set(all_isin_codes).symmetric_difference(set(cbonds_isin_list))

In [74]:
included_isin = all_historical_copies.loc[all_historical_copies['ISIN_Code'].isin(cbonds_isin_list)]

In [75]:
included_isin = included_isin.sort_values(by=['ISIN_Code'])
included_isin

,NCB,historical_date,ISIN_Code,Issuer_Name,Maturity_Date,Coupon_Rate
16466,FI,20171013,AT0000A0KSM6,NOVOMATIC AG,10/27/2017,5
3452,FI,20170714,AT0000A0KSM6,NOVOMATIC AG,27/10/2017,5
12393,FI,20170915,AT0000A0KSM6,NOVOMATIC AG,27/10/2017,5
7395,FI,20170811,AT0000A0KSM6,NOVOMATIC AG,27/10/2017,5
629,FI,20170623,AT0000A0KSM6,NOVOMATIC AG,27/10/2017,5
...,...,...,...,...,...,...
254694,BE,20210507,XS2333391485,Royal Schiphol Group N.V.,22/04/2033,0.75
255321,FI,20210507,XS2337060607,CCEP Fice,06/09/2025,0
255322,FI,20210507,XS2337061670,CCEP Fice,06/09/2029,0.5
255323,FI,20210507,XS2337061753,CCEP Fice,06/05/2033,0.875
255324,FI,20210507,XS2337061837,CCEP Fice,06/05/2041,1.5

In [76]:
unique = included_isin.ISIN_Code.unique()

In [77]:
len(unique)

2054

In [78]:
unique[:5]

array(['AT0000A0KSM6', 'AT0000A0PHV9', 'AT0000A0V7D8', 'AT0000A0X913',
       'AT0000A0XSN7'], dtype=object)

In [79]:
value = pd.DataFrame()

In [80]:
for item in unique:
    info = cbonds.loc[cbonds["ISIN"] == item]
    value = value.append(info, ignore_index = True)

In [81]:
value = value.rename(columns={"ISIN": "ISIN_Code"})

In [82]:
value.head()

,company_name,company_description,relationship_to_bond,sector,industry,ISIN_Code,bond_destination,coupon_rate,total_bond_amount,nominal_amount,...,status,stocks_info,bond_types,Floating rate,Foreign bonds,Green bonds,Securitization,Senior Secured,Senior Unsecured,Zero-coupon bonds
0,Novomatic,The NOVOMATIC Holding is an integrated global ...,Profile,corporate,Media and Entertainment,AT0000A0KSM6,International bonds,5%,"150,000,000 EUR",500 EUR,...,Matured,"Par amount, integral multiple",NaN,no,no,no,no,no,no,no
1,Strabag SE,Strabag SE,Issuer,corporate,Construction and development,AT0000A0PHV9,International bonds,4.75%,"175,000,000 EUR","1,000 EUR",...,Matured,"Par amount, integral multiple",NaN,no,no,no,no,no,no,no
2,Strabag SE,Strabag SE,Issuer,corporate,Construction and development,AT0000A0V7D8,International bonds,4.25%,"100,000,000 EUR","1,000 EUR",...,Matured,"Par amount, integral multiple",NaN,no,no,no,no,no,no,no
3,Kaerntner Elektrizitaets AG,The KELAG concern is one of the leading energy...,Profile,corporate,Power,AT0000A0X913,International bonds,3.25%,"150,000,000 EUR",500 EUR,...,Outstanding,"Par amount, integral multiple",NaN,no,no,no,no,no,no,no
4,Novomatic,The NOVOMATIC Holding is an integrated global ...,Profile,corporate,Media and Entertainment,AT0000A0XSN7,International bonds,4%,"250,000,000 EUR",500 EUR,...,Matured,"Par amount, integral multiple",NaN,no,no,no,no,no,no,no

In [83]:
included_isin

,NCB,historical_date,ISIN_Code,Issuer_Name,Maturity_Date,Coupon_Rate
16466,FI,20171013,AT0000A0KSM6,NOVOMATIC AG,10/27/2017,5
3452,FI,20170714,AT0000A0KSM6,NOVOMATIC AG,27/10/2017,5
12393,FI,20170915,AT0000A0KSM6,NOVOMATIC AG,27/10/2017,5
7395,FI,20170811,AT0000A0KSM6,NOVOMATIC AG,27/10/2017,5
629,FI,20170623,AT0000A0KSM6,NOVOMATIC AG,27/10/2017,5
...,...,...,...,...,...,...
254694,BE,20210507,XS2333391485,Royal Schiphol Group N.V.,22/04/2033,0.75
255321,FI,20210507,XS2337060607,CCEP Fice,06/09/2025,0
255322,FI,20210507,XS2337061670,CCEP Fice,06/09/2029,0.5
255323,FI,20210507,XS2337061753,CCEP Fice,06/05/2033,0.875
255324,FI,20210507,XS2337061837,CCEP Fice,06/05/2041,1.5

In [84]:
combo = included_isin.merge(value, how='left', on='ISIN_Code')

In [85]:
combo.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 256413 entries, 0 to 256412
Data columns (total 30 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   NCB                   255196 non-null  object
 1   historical_date       256413 non-null  object
 2   ISIN_Code             256413 non-null  object
 3   Issuer_Name           256413 non-null  object
 4   Maturity_Date         256413 non-null  object
 5   Coupon_Rate           256413 non-null  object
 6   company_name          256413 non-null  object
 7   company_description   256413 non-null  object
 8   relationship_to_bond  256413 non-null  object
 9   sector                256413 non-null  object
 10  industry              256413 non-null  object
 11  bond_destination      256413 non-null  object
 12  coupon_rate           256413 non-null  object
 13  total_bond_amount     256413 non-null  object
 14  nominal_amount        256413 non-null  object
 15  quarter_created       256413 non-null  object
 16  year_created          256413 non-null  int64
 17  maturity_date         256413 non-null  object
 18  bond_currency         256413 non-null  object
 19  country               256413 non-null  object
 20  status                256413 non-null  object
 21  stocks_info           256413 non-null  object
 22  bond_types            141483 non-null  object
 23  Floating rate         256413 non-null  object
 24  Foreign bonds         256413 non-null  object
 25  Green bonds           256413 non-null  object
 26  Securitization        256413 non-null  object
 27  Senior Secured        256413 non-null  object
 28  Senior Unsecured      256413 non-null  object
 29  Zero-coupon bonds     256413 non-null  object
dtypes: int64(1), object(29)
memory usage: 60.6+ MB

In [86]:
print(combo.shape)

(256413, 30)

In [87]:
combo = combo.sort_values(by=['ISIN_Code', "historical_date"])

In [88]:
combo.head(10)

,NCB,historical_date,ISIN_Code,Issuer_Name,Maturity_Date,Coupon_Rate,company_name,company_description,relationship_to_bond,sector,...,status,stocks_info,bond_types,Floating rate,Foreign bonds,Green bonds,Securitization,Senior Secured,Senior Unsecured,Zero-coupon bonds
4,FI,20170623,AT0000A0KSM6,NOVOMATIC AG,27/10/2017,5,Novomatic,The NOVOMATIC Holding is an integrated global ...,Profile,corporate,...,Matured,"Par amount, integral multiple",NaN,no,no,no,no,no,no,no
12,FI,20170630,AT0000A0KSM6,NOVOMATIC AG,27/10/2017,5.0,Novomatic,The NOVOMATIC Holding is an integrated global ...,Profile,corporate,...,Matured,"Par amount, integral multiple",NaN,no,no,no,no,no,no,no
6,FI,20170707,AT0000A0KSM6,NOVOMATIC AG,27/10/2017,5.0,Novomatic,The NOVOMATIC Holding is an integrated global ...,Profile,corporate,...,Matured,"Par amount, integral multiple",NaN,no,no,no,no,no,no,no
1,FI,20170714,AT0000A0KSM6,NOVOMATIC AG,27/10/2017,5,Novomatic,The NOVOMATIC Holding is an integrated global ...,Profile,corporate,...,Matured,"Par amount, integral multiple",NaN,no,no,no,no,no,no,no
13,FI,20170721,AT0000A0KSM6,NOVOMATIC AG,27/10/2017,5,Novomatic,The NOVOMATIC Holding is an integrated global ...,Profile,corporate,...,Matured,"Par amount, integral multiple",NaN,no,no,no,no,no,no,no
5,FI,20170728,AT0000A0KSM6,NOVOMATIC AG,27/10/2017,5,Novomatic,The NOVOMATIC Holding is an integrated global ...,Profile,corporate,...,Matured,"Par amount, integral multiple",NaN,no,no,no,no,no,no,no
7,FI,20170804,AT0000A0KSM6,NOVOMATIC AG,27/10/2017,5,Novomatic,The NOVOMATIC Holding is an integrated global ...,Profile,corporate,...,Matured,"Par amount, integral multiple",NaN,no,no,no,no,no,no,no
3,FI,20170811,AT0000A0KSM6,NOVOMATIC AG,27/10/2017,5,Novomatic,The NOVOMATIC Holding is an integrated global ...,Profile,corporate,...,Matured,"Par amount, integral multiple",NaN,no,no,no,no,no,no,no
8,FI,20170818,AT0000A0KSM6,NOVOMATIC AG,27/10/2017,5,Novomatic,The NOVOMATIC Holding is an integrated global ...,Profile,corporate,...,Matured,"Par amount, integral multiple",NaN,no,no,no,no,no,no,no
16,FI,20170825,AT0000A0KSM6,NOVOMATIC AG,10/27/2017,5,Novomatic,The NOVOMATIC Holding is an integrated global ...,Profile,corporate,...,Matured,"Par amount, integral multiple",NaN,no,no,no,no,no,no,no

In [89]:
combo=All_of_the_data

NameError: name 'All_of_the_data' is not defined

In [ ]:
# save the unique_improved to csv file
combo.to_csv (r'/Users/gabbyvinco/Desktop/All_of_the_data.csv', index = False, header=True)